### ISSUE TITLE
I think it's time to archive

### ISSUE THREAD

**Issue by benasher44** [Autodesk/coroutineworker#101]
When I wrote CoroutineWorker, the goal was always to help fill a gap in the ecosystem:  multithreaded coroutine support for K/N, until Kotlin's coroutine library shipped stable support.

Stable support has been here for some time now, and this library has (as it was intended) moved into its "museum phase." Now that this library is no longer maintained and is no longer the right choice for modern multiplatform Kotlin, it's time to archive the GitHub repo

**Comment by benasher44** [comment]
@greghaynes  can you help? @C2H6O have Autodesk mobile teams moved on from this library?

**Comment by C2H6O** [comment]
Yeah, we no longer use this library

**Comment by benasher44** [comment]
Sweet! I think the thing to do then would be to pin this issue, archive, and then close this issue (should stay pinned for folks to read it)

**Comment by greghaynes** [comment]
Hey Ben and Alex! Thanks for bringing this up - I can move this repository to public archive as well.

**Comment by greghaynes** [comment]
Archiving prevents you from closing issues so I am closing this now beforehand
