### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by jeremyrempel** [Autodesk/coroutineworker#16]
Documentation makes references to examples. No examples are found in current version

**Comment by benasher44** [comment]
Here's an example usage that I was referring to for `threadSafeSuspendCallback`: https://github.com/Autodesk/coroutineworker/blob/43e0ca89d5a35c928b558e4f4e6ca68cd22674f5/src/nativeMain/kotlin/com/autodesk/coroutineworker/CoroutineWorker.kt#L104. I'll leave this issue open, as I do believe more sample code should be added. I don't have time at the moment unfortunately, but I will try to make time in the coming weeks.

**Comment by benasher44** [comment]
@jeremyrempel it was great meeting you in person this week! I'd appreciate any feedback on #26, as well as what other examples you'd like to see :).

**Comment by benasher44** [comment]
The PR is merged now, but any feedback is still appreciate it! Happy to address in a follow up PR :)

**Comment by benasher44** [comment]
It's been awhile since I've heard back here. I'm going to close this now that the README as a lot more information in it. Feel free to reopen with specifics, if you feel there is more work needed here :)
