### ISSUE TITLE
Release for Kotlin 1.3.41 and kotlinx.coroutines 1.3.0-RC2

### ISSUE THREAD

**Issue by LouisCAD** [Autodesk/coroutineworker#17]
There's no backwards compatibility in Kotlin/Native for now.

**Comment by benasher44** [comment]
Can get to this later this week.

**Comment by benasher44** [comment]
One note: 0.2.1 was the 1.3.41 release. PR coming soon for the coroutines upgrade though.

**Comment by LouisCAD** [comment]
You should update the README.md systematically then, it still shows 1.3.31.

**Comment by benasher44** [comment]
Ah good point. Will update.

0.2.2 has been published. It should be available on maven central in a few hours

**Comment by benasher44** [comment]
README will be fixed with #19
