### ISSUE TITLE
example project could help with adoption

### ISSUE THREAD

**Issue by petrukhnov** [Autodesk/coroutineworker#33]
It would help if there is sample project, that could be downloaded and run on ios/jvm (as separate applications). 
It could show example when use of coroutineworker eliminate need to write platform specific code. 

Now it is not clear, how much boilerplate code required for examples in readme.md.

**Comment by benasher44** [comment]
Thanks! I've added a small sample project w/ added info referencing it in the README. Any thoughts/requests you have would be appreciated on the PR!
