### ISSUE TITLE
Kotlin 1.3.60

### ISSUE THREAD

**Issue by cody1024d** [Autodesk/coroutineworker#35]
This needs a bump for the new version of Kotlin.

In case it helps, I get this error when trying to compile:

```
22:03	Incompatible Kotlin/Native libraries
			There is a third-party library attached to the project that was compiled with an older Kotlin/Native compiler and can't be read in IDE: Gradle: com.autodesk:coroutineworker-iosx64:klib:0.3.1
			Please edit Gradle buildfile(s) and specify library version compatible with Kotlin/Native 1.3.60. Then re-import the project in IDE.
```

**Comment by benasher44** [comment]
Fixed ini #36. Will release a version today

**Comment by benasher44** [comment]
Sorry for the delay– combo of Kotlinconf + waiting for the updated coroutines version to appear iin maven central

**Comment by cody1024d** [comment]
No problem!

I decided to move over to using one of the dev builds of the Kotlin-Native supported coroutines, anyway (as I'm early in development).

Thanks for the update though!
