### ISSUE TITLE
Error building once including library into gradle file:

### ISSUE THREAD

**Issue by tomtaila** [Autodesk/coroutineworker#52]
When trying to build the scheme (in XCode) for my multiplatform module I get:
e: Could not find "/users/me/.gradle/caches/modules-2/files-2.1/com.autodesk/coroutineworker-iosx64/0.5.0/1290d0c69a1bd5384577d2acf1d58d15b1bec/coroutineworker.klib" in [/dir/to/myproject/ios/Pods, /users/me/.konan/klib, /users/me/.konan/kotlin-native-macos-1.3.61/klib/common, /users/me/.konan/kotlin-native-macos-1.3.61/klib/platform/ios_x64].

Caused by simply adding the library to my gradle file:
```implementation("com.autodesk:coroutineworker:0.5.0")```

**Comment by benasher44** [comment]
It looks like you're using Kotlin 1.3.61. 0.5.0 requires Kotlin 1.3.70

**Comment by benasher44** [comment]
For Kotlin 1.3.61, try 0.4.2

**Comment by benasher44** [comment]
I did my best to address this, and there hasn't been a response. Closing.

**Comment by benasher44** [comment]
Feel free to open another issue, if you're still having trouble
