### ISSUE TITLE
Support for tvOS target 

### ISSUE THREAD

**Issue by jstarczewski** [Autodesk/coroutineworker#80]
We are trying to build our app for tvOS target, using coroutineworker, but can not compile it for this target because of no support for tvOS yet. Is it possible to add support for tvOS for coroutineworker?

**Comment by benasher44** [comment]
Thanks for flagging this! I put up a PR that'll add these and watchOS targets too. It'll be available in the next CoroutineWorker release, which we're planning to do once kotlinx.coroutines 1.5.0 (final not RC) is out.
