### ISSUE TITLE
CoroutineWorker vs Coroutines-MT

### ISSUE THREAD

**Issue by slipdef** [Autodesk/coroutineworker#83]
It's was mentioned in several issues here that CoroutineWorker shouldn't be used with Coroutines-MT version. I'm not clear why? Coroutines-MT doesn't solve all issues on native target. The main problem is that it provides a single thread in Default dispatcher while CoroutineWorker has a thread pool. As well no IO dispatcher exists. So if we use Coroutines-MT we're effectively running all IO and computations on a single thread. Does it make sense?

**Comment by benasher44** [comment]
Hi! Yes native-mt doesn't solve everything, but also CoroutineWorker doesn't solve everything either. For the thread pool issue (lack of thread-pool-type dispatcher), that's certainly a native-mt issue, and I recommend filing an issue for them to flag it as gap that should be filled. For the IO dispatcher issue, I think there's a method to create new single thread dispatcher, if I recall. That would be the way to make one that you only use for IO operations.

The main reason is that CoroutineWorker isn't tested with native-mt (see the various issue people have filed). The goal of CoroutineWorker is just to enabled multi-thread coroutine-based K/N applications, while we wait on a full featured kotlinx.coroutines version that works for K/N. CoroutineWorker isn't designed to work with native-mt. It's only meant to provide similar (enough) primitives that allow writing common coroutine-based code for Kotlin multiplatform. So, going back to my original statement, "native-mt doesn't solve everything, but also CoroutineWorker doesn't solve everything either," consider both of these pre-release software (even KMM is labeled as alpha). Eventually, we expect that native-mt won't exist, and kotlinx.coroutines will support K/N outright. At that point, CoroutineWorker should no longer be filling gaps in kotlinx.coroutines and will no longer be needed.
